/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import tes_amp.Laporan;
import tes_amp.class_event;
import tes_amp.class_registrasi;

/**
 *
 * @author HP
 */
public class f_registrasi extends javax.swing.JFrame {

    /**
     * Creates new form f_registrasi
     */
    public static String currentDate;//--> menyimpan tgl secara global

    public f_registrasi() {
        initComponents();
        load_table_event();
        tampilkanTanggal();
        setTanggalListener();
    }

    public void load_table_event() {
        class_registrasi regis = new class_registrasi();
        DefaultTableModel model = regis.showRegistrasi();
        table_event.setModel(model);
        regis.aturTable(table_event);
    }

    public void tampilkanTanggal() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String tanggalSekarang = sdf.format(new Date());
        lbl_tgl.setText(tanggalSekarang);
        currentDate = tanggalSekarang; //simpan ke variabel global
    }

    public static String simpanTanggal() {
        return currentDate;
    }

    private void filterTGL() {
        Date tglAwal = tStartDate.getDate();
        Date tglAkhir = tEndDate.getDate();

        // Cek null terlebih dahulu
        if (tglAwal == null || tglAkhir == null) {
            return; // hentikan supaya tidak error
        }

        class_registrasi regis = new class_registrasi();
        DefaultTableModel model = regis.filterTable(tglAwal, tglAkhir);
        table_event.setModel(model);
        regis.aturTable(table_event);
    }

    private void setTanggalListener() {
        tStartDate.addPropertyChangeListener("date", evt -> {
            if (tStartDate.getDate() != null && tStartDate.getDate() != null) {
                filterTGL();
            }
        });

        tEndDate.addPropertyChangeListener("date", evt -> {
            if (tEndDate.getDate() != null && tEndDate.getDate() != null) {
                filterTGL();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_event = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_tgl = new javax.swing.JLabel();
        tStartDate = new com.toedter.calendar.JDateChooser();
        tEndDate = new com.toedter.calendar.JDateChooser();
        bExport = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        bTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 700));

        jPanel2.setBackground(new java.awt.Color(250, 240, 230));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        table_event.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {}
            },
            new String [] {

            }
        ));
        table_event.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_event.setRequestFocusEnabled(false);
        table_event.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table_event.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_eventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_event);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tabel Data Registrasi Event dan Ujian");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(140, 22, 22));
        jLabel1.setText("REGISTRASI");

        lbl_tgl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_tgl.setText("TANGGAL");

        tStartDate.setBorder(javax.swing.BorderFactory.createTitledBorder("Start Date"));

        tEndDate.setBorder(javax.swing.BorderFactory.createTitledBorder("End Date"));

        bExport.setBackground(new java.awt.Color(255, 51, 51));
        bExport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bExport.setForeground(new java.awt.Color(255, 255, 255));
        bExport.setText("Export PDF");
        bExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExportActionPerformed(evt);
            }
        });

        bReset.setText("Reset");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        bTambah.setBackground(new java.awt.Color(0, 204, 51));
        bTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 424, Short.MAX_VALUE)
                .addComponent(lbl_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(bTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(bReset)
                        .addGap(20, 20, 20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bExport)
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_tgl)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(bReset))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bTambah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bExport)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_eventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_eventMouseClicked
        // TODO add your handling code here:
        int baris = table_event.rowAtPoint(evt.getPoint());

        //pengecekkan tanggal
        if (baris >= 0) {
            String idKegiatan = table_event.getValueAt(baris, 1).toString();
            String namaKegiatan = table_event.getValueAt(baris, 2).toString(); // kolom namaKegiatan
            String tglMulaiStr = table_event.getValueAt(baris, 3).toString(); // kolom tgl mulai
            String tglSelesaiStr = table_event.getValueAt(baris, 4).toString(); // kolom tgl selesai
            String lokasi = table_event.getValueAt(baris, 5).toString(); // kolom tgl selesai
            String parentUjian = table_event.getValueAt(baris, 6).toString(); // kolom tgl selesai

            String[] options = {"Ubah Data", "Tambah Peserta", "Batal"};

            int choice = JOptionPane.showOptionDialog(
                    null,
                    "Pilih aksi yang ingin dilakukan:",
                    "Konfirmasi",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[0]
            );

            if (choice == 0) {
                // Aksi jika pilih Ubah Data
                popUp_tambah_data_registrasi regis = new popUp_tambah_data_registrasi(this);
                regis.setVisible(true);
                regis.tampil_data(idKegiatan, namaKegiatan, tglMulaiStr, tglMulaiStr, lokasi, parentUjian);
                regis.tampilan_edit_regist();
            } else if (choice == 1) {
                // Aksi jika pilih Tambah Peserta
                try {
                // Format tanggal dari database (biasanya yyyy-MM-dd)
                SimpleDateFormat sdfDB = new SimpleDateFormat("yyyy-MM-dd");
                Date tglMulai = sdfDB.parse(tglMulaiStr);
                Date tglSelesai = sdfDB.parse(tglSelesaiStr);

                // Ambil tanggal hari ini dari lbl_tgl (format dd-MM-yyyy)
                SimpleDateFormat sdfNow = new SimpleDateFormat("dd-MM-yyyy");
                Date tanggalSekarang = sdfNow.parse(currentDate);

                // Bandingkan tanggal
                if (!tanggalSekarang.before(tglMulai) && !tanggalSekarang.after(tglSelesai)) {
                    // Hari ini di antara tgl_mulai dan tgl_selesai
                    popUp_tambah_registrasi tambah_regis = new popUp_tambah_registrasi(idKegiatan);
                    tambah_regis.setVisible(true);
                    tambah_regis.namaKegiatan(namaKegiatan); // set nama kegiatan di panel tambah registrasi
                    JOptionPane.showMessageDialog(null,
                            "Periode registrasi masih berlangsung sampai " + tglSelesaiStr);
                } else if (tanggalSekarang.before(tglMulai)) {
                    // Hari ini sebelum tgl_mulai 
                    /*popUp_data_registrasi data_regis = new popUp_data_registrasi();
                    data_regis.setVisible(true); */
                    JOptionPane.showMessageDialog(null,
                            "Periode registrasi belum dimulai.");
                } else if (tanggalSekarang.after(tglSelesai)) {
                    // Hari ini setlah tgl_selesai 
                    popUp_data_registrasi data = new popUp_data_registrasi();
                    data.tampilDataAKhir(idKegiatan);
                    data.setVisible(true);
                    JOptionPane.showMessageDialog(null,
                            "Periode registrasi sudah berakhir.");

                }

            } catch (Exception e) {
                System.out.println(e);
            }
                
            } else {
                // choice == 2 atau dialog ditutup
                // Tidak melakukan apapun → otomatis menutup
//                System.out.println("Dialog ditutup tanpa aksi");
            }  
        }
    }//GEN-LAST:event_table_eventMouseClicked

    private void bExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExportActionPerformed
        // TODO add your handling code here:
        Date awal = tStartDate.getDate();
        Date akhir = tEndDate.getDate();
        Laporan lap = new Laporan();
        lap.generateLaporanRegistrasi(awal, akhir);
    }//GEN-LAST:event_bExportActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        tStartDate.setDate(null);
        tEndDate.setDate(null);
        load_table_event();
    }//GEN-LAST:event_bResetActionPerformed

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
        // TODO add your handling code here:
        popUp_tambah_data_registrasi tambahRegist = new popUp_tambah_data_registrasi(this);
        tambahRegist.setVisible(true);
        tambahRegist.tampilan_tambah_regist();
    }//GEN-LAST:event_bTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExport;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_tgl;
    private com.toedter.calendar.JDateChooser tEndDate;
    private com.toedter.calendar.JDateChooser tStartDate;
    private javax.swing.JTable table_event;
    // End of variables declaration//GEN-END:variables
}
