/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tes_amp.class_event;
import tes_amp.koneksi;

/**
 *
 * @author HP
 */
public class popUp_tambah_event extends javax.swing.JFrame {

    /**
     * Creates new form popUp_tambah_event
     */
    private f_event p_tambahEvent;

    public popUp_tambah_event(f_event tambahEvent) {
        initComponents();
        this.p_tambahEvent = tambahEvent;
        reset();
        autoID();
    }

    void reset() {
        t_idevent.setText(null);
        t_nama.setText(null);
        t_tgl_mulai.setCalendar(null);
        t_tgl_selesai.setCalendar(null);
        t_lokasi.setText(null);
        c_kategori.setSelectedItem(null);
        t_keterangan.setText(null);
    }

    public void tampilan_tambah_event() {
        b_ubah.setVisible(false);
        b_hapus.setVisible(false);
    }

    public void tampilan_edit_event() {
        b_simpan.setVisible(false);
    }

    public void tampil_data(String id, String nama, String tglMulai, String tglAkhir,
            String lokasi, String kategori, String keterangan) {

        t_idevent.setText(id);
        t_nama.setText(nama);

        // Format tanggal sesuai yang disimpan di database
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        try {
            if (tglMulai != null && !tglMulai.isEmpty()) {
                Date dateMulai = sdf.parse(tglMulai);
                t_tgl_mulai.setDate(dateMulai);
            } else {
                t_tgl_mulai.setDate(null);
            }

            if (tglAkhir != null && !tglAkhir.isEmpty()) {
                Date dateAkhir = sdf.parse(tglAkhir);
                t_tgl_selesai.setDate(dateAkhir);
            } else {
                t_tgl_selesai.setDate(null);
            }

        } catch (ParseException e) {
            e.printStackTrace();
            // Jika parsing gagal, kosongkan JDateChooser agar tidak error
            t_tgl_mulai.setDate(null);
            t_tgl_selesai.setDate(null);
        }

        t_lokasi.setText(lokasi);
        c_kategori.setSelectedItem(kategori);
        t_keterangan.setText(keterangan);
    }

    private void autoID() {
        try {
            String sql = "SELECT MAX(ID_event) FROM event_ujian";
            Connection con = koneksi.konek();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            String id = "KGT001"; //default awal
            if (rs.next()) {
                String maxID = rs.getString(1);
                if (maxID != null) {
                    int num = Integer.parseInt(maxID.substring(3)); //ambil angka setelah "KAT"
                    num++;
                    id = String.format("KGT%03d", num); //format ulang jadi 3 digit
                }
            }

            t_idevent.setText(id);
        } catch (SQLException sQLException) {
            JOptionPane.showMessageDialog(null, "Error saat generate Id Kegiatan!");
            System.out.println(sQLException);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_tgl_mulai = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        t_lokasi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_kategori = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t_keterangan = new javax.swing.JTextArea();
        b_simpan = new javax.swing.JButton();
        b_ubah = new javax.swing.JButton();
        b_hapus = new javax.swing.JButton();
        t_idevent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_tgl_selesai = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tanggal Mulai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tanggal Selesai");

        t_lokasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_lokasiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Kategori");

        c_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Event", "Ujian", "Registrasi" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Keterangan");

        t_keterangan.setColumns(20);
        t_keterangan.setRows(5);
        jScrollPane1.setViewportView(t_keterangan);

        b_simpan.setBackground(new java.awt.Color(0, 204, 0));
        b_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_simpan.setForeground(new java.awt.Color(255, 255, 255));
        b_simpan.setText("Simpan");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        b_ubah.setBackground(new java.awt.Color(255, 102, 0));
        b_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_ubah.setForeground(new java.awt.Color(255, 255, 255));
        b_ubah.setText("Ubah");
        b_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ubahActionPerformed(evt);
            }
        });

        b_hapus.setBackground(new java.awt.Color(255, 51, 51));
        b_hapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_hapus.setForeground(new java.awt.Color(255, 255, 255));
        b_hapus.setText("Hapus");
        b_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_hapusActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("ID ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nama Kegiatan ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Lokasi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(t_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(254, 254, 254))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t_tgl_mulai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(t_tgl_selesai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t_nama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(t_idevent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(b_simpan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(b_ubah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(b_hapus))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(c_kategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                .addGap(168, 168, 168))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_idevent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tgl_mulai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_tgl_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_lokasi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(b_ubah)
                    .addComponent(b_hapus))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        // TODO add your handling code here:
        class_event event = new class_event();
        event.setID_event(t_idevent.getText());
        event.setNama_event(t_nama.getText());

        //ambil tgl mulai dari komponen kalender
        Date tglMulaiDate = t_tgl_mulai.getDate();
        String tglMulai = null;
        if (tglMulaiDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglMulai = new SimpleDateFormat("yyyy-MM-dd").format(tglMulaiDate);
        }
        event.setTgl_mulai(tglMulai);

        //ambil tgl mulai dari komponen kalender
        Date tglAkhirDate = t_tgl_selesai.getDate();
        String tglAkhir = null;
        if (tglAkhirDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglAkhir = new SimpleDateFormat("yyyy-MM-dd").format(tglAkhirDate);
        }
        event.setTgl_selesai(tglAkhir);

        event.setLokasi(t_lokasi.getText());
        event.setJenis(c_kategori.getSelectedItem().toString());
        event.setKeterangan(t_keterangan.getText());
        event.setiD_user("US01");

        event.tambah_event();
        // setelah berhasil tambah, refresh tabel di frame utama
        if (p_tambahEvent != null) {
            p_tambahEvent.load_table_event(); // panggil fungsi reload
        }
        reset();
        dispose();

    }//GEN-LAST:event_b_simpanActionPerformed

    private void t_lokasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_lokasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_lokasiActionPerformed

    private void b_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ubahActionPerformed
        // TODO add your handling code here:
        class_event event = new class_event();
        event.setID_event(t_idevent.getText());
        event.setNama_event(t_nama.getText());

        //ambil tgl mulai dari komponen kalender
        Date tglMulaiDate = t_tgl_mulai.getDate();
        String tglMulai = null;
        if (tglMulaiDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglMulai = new SimpleDateFormat("yyyy-MM-dd").format(tglMulaiDate);
        }
        event.setTgl_mulai(tglMulai);

        //ambil tgl mulai dari komponen kalender
        Date tglAkhirDate = t_tgl_selesai.getDate();
        String tglAkhir = null;
        if (tglAkhirDate != null) {
            // Mengubah tanggal lahir menjadi format "yyyy-MM-dd"
            tglAkhir = new SimpleDateFormat("yyyy-MM-dd").format(tglAkhirDate);
        }
        event.setTgl_selesai(tglAkhir);

        event.setLokasi(t_lokasi.getText());
        event.setJenis(c_kategori.getSelectedItem().toString());
        event.setKeterangan(t_keterangan.getText());
        event.setiD_user("US01");

        event.ubah_event();
        // setelah berhasil tambah, refresh tabel di frame utama
        if (p_tambahEvent != null) {
            p_tambahEvent.load_table_event(); // panggil fungsi reload
        }
        reset();
        dispose();
    }//GEN-LAST:event_b_ubahActionPerformed

    private void b_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_hapusActionPerformed
        // TODO add your handling code here:
        class_event event = new class_event();
        event.setID_event(t_idevent.getText());
        event.hapus_event();
        // setelah berhasil tambah, refresh tabel di frame utama
        if (p_tambahEvent != null) {
            p_tambahEvent.load_table_event(); // panggil fungsi reload
        }
        dispose();
    }//GEN-LAST:event_b_hapusActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_hapus;
    private javax.swing.JButton b_simpan;
    private javax.swing.JButton b_ubah;
    private javax.swing.JComboBox<String> c_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_idevent;
    private javax.swing.JTextArea t_keterangan;
    private javax.swing.JTextField t_lokasi;
    private javax.swing.JTextField t_nama;
    private com.toedter.calendar.JDateChooser t_tgl_mulai;
    private com.toedter.calendar.JDateChooser t_tgl_selesai;
    // End of variables declaration//GEN-END:variables
}
