/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import tes_amp.koneksi;

/**
 *
 * @author HP
 */
public class popUp_cari_anggota extends javax.swing.JFrame {

    /**
     * Creates new form popUp_cari_anggota
     */
    private popUp_tambah_registrasi pnRegistrasi;
    public popUp_cari_anggota(popUp_tambah_registrasi pn_regitrasi) {
        initComponents();
        this.pnRegistrasi = pn_regitrasi;
        load_table_anggota();
    }
    
    void load_table_anggota(){
     DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("ID Anggota");
        model.addColumn("Nama Anggota");
        model.addColumn("Status");
        int no = 1;
       //Query SL utk mengambil semua data dari tabel
       String sql = "SELECT * FROM anggota";
       
       try {
           Connection con = koneksi.konek();
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(sql);
           
           while (rs.next()) {
               //ambil data kolom id dan nama kategori
               String id = rs.getString("ID_anggota");
               String nama = rs.getString("nama_anggota");
               String status = rs.getString("status");
               //membuat array berisi data satu baris
               Object[] baris = {no++, id, nama, status };
               //menambahkan array ke dlm tabel
               model.addRow(baris);
           }
       } catch (SQLException sQLException) {
           //menampilkan pesan error
           JOptionPane.showMessageDialog(null, "Gagal mengambil data!");
           System.out.println(sQLException);
       }
       table_data_anggota.setModel(model);
       atur_table();
    }
    
    void atur_table() {
        // Warna lembut untuk header
        table_data_anggota.getTableHeader().setBackground(new Color(102, 204, 255)); // biru pucat (baby blue)
        table_data_anggota.getTableHeader().setForeground(Color.BLACK);
        table_data_anggota.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));

        // Warna sel tabel (hitam putih natural)
        table_data_anggota.setBackground(Color.WHITE);
        table_data_anggota.setForeground(Color.BLACK);
        table_data_anggota.setGridColor(Color.LIGHT_GRAY);
        table_data_anggota.setSelectionBackground(new Color(220, 240, 255)); // biru muda saat dipilih
        table_data_anggota.setSelectionForeground(Color.BLACK);

        // === Mengatur rata tengah teks di tabel ===
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        // Rata tengah untuk semua kolom
        for (int i = 0; i < table_data_anggota.getColumnCount(); i++) {
            table_data_anggota.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        // Rata tengah header kolom juga
        ((DefaultTableCellRenderer) table_data_anggota.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(SwingConstants.CENTER);

        // Mengatur lebar kolom
        table_data_anggota.getColumnModel().getColumn(0).setPreferredWidth(30);  // No
        table_data_anggota.getColumnModel().getColumn(1).setPreferredWidth(100); // ID Anggota
        table_data_anggota.getColumnModel().getColumn(2).setPreferredWidth(150); // Nama Anggota
        table_data_anggota.getColumnModel().getColumn(3).setPreferredWidth(100); // Status
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_cari_nama = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_data_anggota = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("CARI DATA ANGGOTA");

        t_cari_nama.setBorder(javax.swing.BorderFactory.createTitledBorder("Cari Nama Anggota"));
        t_cari_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                t_cari_namaKeyReleased(evt);
            }
        });

        table_data_anggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_data_anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_data_anggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_data_anggota);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(t_cari_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(t_cari_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_cari_namaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cari_namaKeyReleased
        // TODO add your handling code here:
        String kataKunci = t_cari_nama.getText();
      
        try {
            DefaultTableModel model = (DefaultTableModel)table_data_anggota.getModel();
            model.setRowCount(0);//kosongkan tabel
            
            Connection con = koneksi.konek();
            String sql = "SELECT * FROM anggota WHERE nama_anggota LIKE ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, "%"+kataKunci+"%");
            ResultSet rs = ps.executeQuery();
            
            int no = 1;
            while(rs.next()){
                model.addRow(new Object[]{
                no++,
                rs.getString("ID_anggota"),
                rs.getString("nama_anggota"),
                rs.getString("status")
                });
            }
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_t_cari_namaKeyReleased

    private void table_data_anggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_data_anggotaMouseClicked
        // TODO add your handling code here:
        int barisdipilih = table_data_anggota.rowAtPoint(evt.getPoint());
        
        if (barisdipilih >= 0) {
            String id = table_data_anggota.getValueAt(barisdipilih, 1).toString();
            String nama = table_data_anggota.getValueAt(barisdipilih, 2).toString();
            String status = table_data_anggota.getValueAt(barisdipilih, 3).toString();
            
          
           pnRegistrasi.tampilData(id, nama, status);
           pnRegistrasi.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_table_data_anggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUp_cari_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUp_cari_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUp_cari_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUp_cari_anggota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t_cari_nama;
    private javax.swing.JTable table_data_anggota;
    // End of variables declaration//GEN-END:variables
}
