/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import tes_amp.koneksi;
import tes_amp.class_registrasi;

/**
 *
 * @author HP
 */
public class popUp_tambah_registrasi extends javax.swing.JFrame {

    /**
     * Creates new form popUp_tambah_registrasi
     */
    DefaultTableModel modelRegistrasi;
    ArrayList<String[]> daftarAnggota = new ArrayList<>();

    public popUp_tambah_registrasi(String idKegiatan) {
        initComponents();
        setTableModel();
        autoID(idKegiatan);
        reset();
    }

    void reset() {
        t_id.setText(null);
        t_nama.setText(null);
        t_status.setText(null);
    }

    void setTableModel() {
        modelRegistrasi = new DefaultTableModel(new String[]{
            "No",
            "ID Anggota",
            "Nama Anggota",
            "Status"},
                0);
        table_peserta.setModel(modelRegistrasi);
    }

    public void tampilData(String id, String nama, String status) {
        t_id.setText(id);
        t_nama.setText(nama);
        t_status.setText(status);
    }

    public void namaKegiatan(String namaKegiatan) {
        lbl_Kegiatan.setText(namaKegiatan);
    }

    String idKegiatan(String namaKegiatan) {
        try {
            String sql = "SELECT * FROM event_ujian WHERE nama_event=?";
            Connection con = koneksi.konek();
            //  Statement st = con.createStatement();
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, namaKegiatan);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                return rs.getString("ID_event");
            }
        } catch (SQLException e) {
            //jika error. kembali string kosong
            return "";
        }
        return "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_dasar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_cari = new javax.swing.JButton();
        t_id = new javax.swing.JTextField();
        t_nama = new javax.swing.JTextField();
        t_status = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_peserta = new javax.swing.JTable();
        b_simpan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_Kegiatan = new javax.swing.JLabel();
        b_tambah = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        bDetail = new javax.swing.JButton();
        bBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_dasar.setBackground(new java.awt.Color(255, 255, 255));
        pn_dasar.setPreferredSize(new java.awt.Dimension(484, 539));

        jLabel1.setText("DAFTAR REGISTRASI PESERTA EVENT ATAU UJIAN PORSIGAL ");

        b_cari.setText("Cari Data Anggota");
        b_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cariActionPerformed(evt);
            }
        });

        t_id.setBorder(javax.swing.BorderFactory.createTitledBorder("ID Anggota"));

        t_nama.setBorder(javax.swing.BorderFactory.createTitledBorder("Nama Anggota"));
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        t_status.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        table_peserta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_peserta);

        b_simpan.setBackground(new java.awt.Color(0, 204, 0));
        b_simpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_simpan.setForeground(new java.awt.Color(255, 255, 255));
        b_simpan.setText("Save");
        b_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_simpanActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Kegiatan :");

        lbl_Kegiatan.setText(".........");

        b_tambah.setBackground(new java.awt.Color(0, 204, 255));
        b_tambah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_tambah.setForeground(new java.awt.Color(255, 255, 255));
        b_tambah.setText("Add");
        b_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tambahActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Registrasi     :");

        lbl_id.setText(".........");

        bDetail.setBackground(new java.awt.Color(153, 153, 153));
        bDetail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bDetail.setForeground(new java.awt.Color(255, 255, 255));
        bDetail.setText("Detail");
        bDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDetailActionPerformed(evt);
            }
        });

        bBack.setBackground(new java.awt.Color(255, 0, 102));
        bBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bBack.setForeground(new java.awt.Color(255, 255, 255));
        bBack.setText("<Back");
        bBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_dasarLayout = new javax.swing.GroupLayout(pn_dasar);
        pn_dasar.setLayout(pn_dasarLayout);
        pn_dasarLayout.setHorizontalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_dasarLayout.createSequentialGroup()
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bBack)
                        .addGap(23, 23, 23)
                        .addComponent(bDetail)
                        .addGap(18, 18, 18)
                        .addComponent(b_simpan))
                    .addGroup(pn_dasarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_dasarLayout.createSequentialGroup()
                                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b_cari)
                                    .addComponent(t_id)
                                    .addComponent(t_nama)
                                    .addComponent(t_status, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_tambah))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addGroup(pn_dasarLayout.createSequentialGroup()
                                    .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_id, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbl_Kegiatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(26, 26, 26))
        );
        pn_dasarLayout.setVerticalGroup(
            pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_dasarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_id))
                .addGap(8, 8, 8)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_Kegiatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_cari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_tambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pn_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_simpan)
                    .addComponent(bDetail)
                    .addComponent(bBack))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dasar, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_dasar, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void b_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_simpanActionPerformed
        // TODO add your handling code here:
        class_registrasi regis = new class_registrasi();

        regis.setIdRegistrasi(lbl_id.getText());
        regis.setIdKegiatan(idKegiatan(lbl_Kegiatan.getText()));
        try {
            for (String[] item : daftarAnggota) {
                String namaAnggota = item[1];

                try {
                    String sql = "SELECT * FROM anggota WHERE nama_anggota=?";
                    Connection con = koneksi.konek();
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, namaAnggota);
                    ResultSet rs = ps.executeQuery();

                    if (rs.next()) {
                        String idAnggota = rs.getString("ID_anggota");
                        regis.setIdAnggota(idAnggota);
                        regis.simpanRegis();

                    }
                    rs.close();
                    ps.close();
                    con.close();
                    
                } catch (SQLException e) {
                    //jika error. kembali string kosong
                    System.out.println(e);
                }
            }
            // 🧹 Reset daftarAnggota agar kosong untuk input berikutnya
                    daftarAnggota.clear();

                    // 🧹 Reset tampilan tabel (hapus semua baris)
                    DefaultTableModel model = (DefaultTableModel) table_peserta.getModel();
                    model.setRowCount(0);
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");

        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan");
        }
        
    }//GEN-LAST:event_b_simpanActionPerformed

    private void b_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cariActionPerformed
        // TODO add your handling code here:
        new popUp_cari_anggota(this).setVisible(true);
    }//GEN-LAST:event_b_cariActionPerformed

    private void b_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tambahActionPerformed
        // TODO add your handling code here:
        String id = t_id.getText();
        String nama = t_nama.getText();
        String status = t_status.getText();
        daftarAnggota.add(new String[]{
            id, nama, status
        });
        modelRegistrasi.addRow(new Object[]{
            modelRegistrasi.getRowCount() + 1,
            id, nama, status
        });
        reset();
    }//GEN-LAST:event_b_tambahActionPerformed

    private void bDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDetailActionPerformed
        // TODO add your handling code here:
        String idRegis = lbl_id.getText(); // ambil ID registrasi dari label

        popUp_data_registrasi detail_regis = new popUp_data_registrasi(); // kirim ke frame kedua
        detail_regis.setVisible(true);
        detail_regis.tampilData(idRegis);
    }//GEN-LAST:event_bDetailActionPerformed

    private void bBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bBackActionPerformed

    private void autoID(String idKegiatan) {
        try {
        Connection con = koneksi.konek();
        String sqlCek = "SELECT ID_registrasi FROM registrasi r " +
                        "JOIN event_ujian e ON r.ID_event_ujian = e.ID_event " +
                        "WHERE e.ID_event = ? " +
                        "AND CURDATE() BETWEEN e.tgl_mulai AND e.tgl_selesai " +
                        "LIMIT 1";
        PreparedStatement psCek = con.prepareStatement(sqlCek);
        psCek.setString(1, idKegiatan);
        ResultSet rsCek = psCek.executeQuery();

        String idRegistrasi;

        if (rsCek.next()) {
            // Jika sudah ada registrasi untuk kegiatan ini di periode aktif
            idRegistrasi = rsCek.getString("ID_registrasi");
        } else {
            // Kalau belum ada, buat ID baru berdasarkan ID terbesar
            String sqlMax = "SELECT MAX(ID_registrasi) FROM registrasi";
            Statement st = con.createStatement();
            ResultSet rsMax = st.executeQuery(sqlMax);

            int nextNum = 1;
            if (rsMax.next() && rsMax.getString(1) != null) {
                String maxID = rsMax.getString(1);
                nextNum = Integer.parseInt(maxID.substring(3)) + 1;
            }

            idRegistrasi = String.format("REG%03d", nextNum);
            rsMax.close();
            st.close();
        }

        lbl_id.setText(idRegistrasi);

        rsCek.close();
        psCek.close();
        con.close();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error saat generate ID Registrasi: " + e.getMessage());
        e.printStackTrace();
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popUp_tambah_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popUp_tambah_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popUp_tambah_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popUp_tambah_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
     /*   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popUp_tambah_registrasi().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBack;
    private javax.swing.JButton bDetail;
    private javax.swing.JButton b_cari;
    private javax.swing.JButton b_simpan;
    private javax.swing.JButton b_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Kegiatan;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JPanel pn_dasar;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_status;
    private javax.swing.JTable table_peserta;
    // End of variables declaration//GEN-END:variables
}
